{% set name = "afwizard" %}
{% set version = "1.0.0b9" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/afwizard-{{ version }}.tar.gz
  sha256: 22b609fdc6a6bb7a9b4d2c208bc5ac037c8338c9f64b6d926a392f9eed0c2279

build:
  entry_points:
    - afwizard = afwizard.__main__:main
    - copy_afwizard_notebooks = afwizard.paths:copy_notebooks
    - extract_opals_schema = afwizard.opals:_automated_opals_schema
    - upgrade_filter_library = afwizard.library:upgrade_filter_library
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - pip
    - python >=3.9
  run:
    - afwizard-library
    - click
    - gdal
    - geojson
    - ipyfilechooser
    - ipyleaflet
    - ipython
    - ipywidgets >=8
    - ipywidgets-jsonschema
    - jsonmerge
    - jsonschema <4
    - jupyter-resource-usage
    - jupyterlab
    - numpy
    - pdal
    - pillow
    - pooch
    - pyproj
    - pyrsistent
    - python >=3.9
    - python-pdal
    - pytools
    - wrapt
    - xdg
    - xmltodict

test:
  imports:
    - afwizard
  commands:
    - afwizard --help
    - copy_afwizard_notebooks --help
    - extract_opals_schema --help
    - upgrade_filter_library --help

about:
  home: https://pypi.org/project/afwizard/
  summary: Adaptive Filtering Wizard
  license: MIT
  license_file: LICENSE.md
  dev_url: https://github.com/ssciwr/afwizard
  doc_url: https://afwizard.readthedocs.io/

extra:
  recipe-maintainers:
    - dokempf
