{% set name = "afwizard" %}
{% set version = "1.0.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/afwizard-{{ version }}.tar.gz
  sha256: ba45a2bd98ca813ae4ec1073f921d78e5d4452f54d1a9fec58ed6d0f86292e3e

build:
  entry_points:
    - afwizard = afwizard.__main__:main
    - copy_afwizard_notebooks = afwizard.paths:copy_notebooks
    - extract_opals_schema = afwizard.opals:_automated_opals_schema
    - upgrade_filter_library = afwizard.library:upgrade_filter_library
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - pip
    - python {{ python_min }}
    - setuptools
  run:
    - afwizard-library
    - click
    - gdal
    - geojson
    - ipyfilechooser
    - ipyleaflet
    - ipython
    - ipywidgets >=8
    - ipywidgets-jsonschema
    - jsonmerge
    - jsonschema <4
    - jupyter-resource-usage
    - jupyterlab
    - numpy
    - pdal
    - pillow
    - pooch
    - pyproj
    - pyrsistent
    - python >={{ python_min }}
    - python-pdal
    - pytools
    - wrapt
    - xdg
    - xmltodict

test:
  requires:
    - python {{ python_min }}
  imports:
    - afwizard
  commands:
    - afwizard --help
    - copy_afwizard_notebooks --help
    - extract_opals_schema --help
    - upgrade_filter_library --help

about:
  home: https://pypi.org/project/afwizard/
  summary: Adaptive Filtering Wizard
  license: MIT
  license_file: LICENSE.md
  dev_url: https://github.com/ssciwr/afwizard
  doc_url: https://afwizard.readthedocs.io/

extra:
  recipe-maintainers:
    - dokempf
